### ISSUE TITLE
Export not working if reframework/data doesn't exist

### ISSUE THREAD

**Issue by Toufailleur** [valen214/mhr_charm_exporter#1]
When exporting charms, if the folder "data" in "reframework" doesn't exist, export won't work. Just adding the folder make it work. You might only need to make the folder in your zip.
Thanks for your work.

**Comment by valen214** [comment]
noted, thanks for telling, I guess you're using the dll(-coupled) version?

I probably going for creating a folder with the dll instead of putting it within the zip,

reframework blocked the 'io' module in lua so ... but with lua, I'm using functions provided by their kit I think they handled that already


I'd probably get back on this/add the change only after the August update.

**Comment by Toufailleur** [comment]
I'm currently using your last release, with the DLL then.

Thanks for your quick reply, happy hunting.

**Comment by valen214** [comment]
I have made further update, you might want to take a look,
because c++17 wasn't working well with lua in the previous release, and lua documentation is a pain.
Compiling lua with cpp myself might not help because I'm uncertain whether reframework does the same too.

but now it should be fine with [the latest release (v2.1.3)](https://github.com/valen214/mhr_charm_exporter/releases/tag/v2.1.3)

closing the issue, feel free to reopen it if it happens again
